#!/usr/bin/env bash

set -e

rootdir=$1
script=$(realpath $2)

echo Creating $rootdir
mkdir $rootdir

echo Changing directory to $rootdir
cd $rootdir

echo Executing the script: $script
bash $script

cd - > /dev/null

echo Created the following directory structure in $rootdir
tree $rootdir
